config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  resources :type_of_activities
  resources :projects
  resources :collegials
  resources :type_of_movements
  resources :decisions
  resources :financial_indicators
  resources :indicator_values
  resources :inflows_outflows
  post 'inflows_outflows/export'
  resources :type_of_decisions

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/indicator_value.rb
# == Schema Information
#
# Table name: indicator_values
#
#  id           :integer          not null, primary key
#  project_id   :integer
#  indicator_id :integer
#  value        :string
#  date_i       :date
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
# Indexes
#
#  index_indicator_values_on_indicator_id  (indicator_id)
#  index_indicator_values_on_project_id    (project_id)
#

class IndicatorValue < ApplicationRecord
  belongs_to :project
  belongs_to :indicator, class_name: "FinancialIndicator"
end

app/controllers/indicator_values_controller.rb
class IndicatorValuesController < ApplicationController
  before_action :check_user!

  def index
    @indicator = IndicatorValue.all
  end

  def show
    @indicator = IndicatorValue.find(params[:id])
  end

  def new
    @indicator = IndicatorValue.new
  end
  
  def edit
    @indicator = IndicatorValue.find(params[:id])
  end

  def create
    @indicator = IndicatorValue.new(indicator_params)
    @indicator.save

    redirect_to @indicator
  end

  def update
    @indicator = IndicatorValue.find(params[:id])
    @indicator.assign_attributes(indicator_params)
    if @indicator.save
      flash[:success] = "Изменения сохранены."
      render :show
    else
      flash[:error] = "Ошибка! Изменения не сохранены"
      render :show
    end
  end

  def destroy
    @indicator = IndicatorValue.find(params[:id])
    @indicator.destroy

    redirect_to indicators_path
  end

  private
  def indicator_params
    params.require(:indicator_value).permit(:project_id, :indicator_id, :date_i, :value)
  end
end

app/helpers/indicator_values_helper.rb
module IndicatorValuesHelper
end

app/views/indicator_values/edit.html.erb
<h1>Изменить</h1>
<%= form_for (@indicator) do |f| %>
  <%= f.label 'Название проекта' %>
  <%= f.collection_select :project_id, Project.all, :id, :name %>
  <%= f.label 'Название финансовго индикатора' %>
  <%= f.collection_select :indicator_id, FinancialIndicator.all, :id, :name %>
  <%= f.label :Значение %>
  <%= f.text_field :value %>
  <%= f.label :Дата %>
  <%= f.date_field (:date_i) %>
  <%= f.submit :Сохранить%>
<% end %>

<%= link_to 'Назад', indicator_values_path %>

app/views/indicator_values/index.html.erb
<h1>Значение</h1>
<div class="form-group">
  <%= link_to 'Новое значение', new_indicator_value_path, class: 'btn btn-primary' %>
</div>
<table class="table table-striped">
  <th>Проект</th>
  <th>Название финансового показателя</th>
  <th>Значение</th>
  <th>Дата</th>
  <% @indicator.each do |indicator| %>
    <tr>
      <td><%= link_to indicator.project.name, indicator %></td>
      <td><%= link_to indicator.indicator.name, indicator%></td>
      <td><%= indicator.value %></td>
      <td><%= indicator.date_i%></td>
    </tr>
  <% end %>
</table>

app/views/indicator_values/new.html.erb
<h1>Новое значение</h1>
<%= form_for(@indicator) do |f| %>
  <p>
    <%= f.label 'Название проекта' %><br>
    <%= f.collection_select :project_id, Project.all, :id, :name %>
  </p>
  <p>
    <%= f.label 'Финансовый индикатор' %><br>
    <%= f.collection_select :indicator_id, FinancialIndicator.all, :id, :name %>
  </p>
  <p>
    <%= f.label :Значение %><br>
    <%= f.text_field :value %>
  </p>
  <p>
    <%= f.label :Дата %><br>
    <%= f.date_field :date_i %>
  </p>
  <p>
    <%= f.submit 'Создать' %>
  </p>
  <%= link_to 'Назад', indicator_values_path %>
<% end %>

app/views/indicator_values/show.html.erb
<h1>Название:</h1>
<p> 
  <%= @indicator.project.name %><br><br>
  <%= @indicator.value %>
  <%= link_to 'Изменить', edit_indicator_value_path %>
  <%= link_to 'Удалить', indicator_value_path(@indicator), method: :delete, data: { confirm: 'Вы уверены?' } %>
</p>
<%= link_to 'Назад', indicator_values_path %>