config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  resources :type_of_activities
  resources :projects
  resources :collegials
  resources :type_of_movements
  resources :decisions
  resources :financial_indicators
  resources :indicator_values
  resources :inflows_outflows
  post 'inflows_outflows/export'
  resources :type_of_decisions

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/collegial.rb
# == Schema Information
#
# Table name: collegials
#
#  id         :integer          not null, primary key
#  name       :string
#  address    :string
#  phone      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Collegial < ApplicationRecord
  has_many :decisions
end

app/controllers/collegials_controller.rb
class CollegialsController < ApplicationController
  before_action :check_user!


  def index
    @collegial = Collegial.all
  end

  def show
    @collegial = Collegial.find(params[:id])
  end

  def new
    @collegial = Collegial.new
  end
  
  def edit
    @collegial = Collegial.find(params[:id])
  end

  def create
    @collegial = Collegial.new(collegial_params)
    @collegial.save

    redirect_to @collegial
  end

  def update
    @collegial = Collegial.find(params[:id])
    @collegial.assign_attributes(collegial_params)
    if @collegial.save
      flash[:success] = "Изменения сохранены."
      render :show
    else
      flash[:error] = "Ошибка! Изменения не сохранены"
      render :show
    end
  end

  def destroy
    @collegial = Collegial.find(params[:id])
    @collegial.destroy

    redirect_to collegial_index_path
  end

  private
  def collegial_params
    params.require(:collegial).permit(:name, :address, :phone)
  end
end

app/helpers/collegials_helper.rb
module CollegialsHelper
end

app/views/collegials/edit.html.erb
<h1>Изменение Типа деятельности</h1>
 
<%= form_for (@collegial) do |f| %>
  <%= f.label :Название%>
  <%= f.text_field :name %>
  <%= f.label :Адрес%>
  <%= f.text_field :address %>
  <%= f.label :Телефон%>
  <%= f.text_field :phone %>
  <%= f.submit :Сохранить%>
<% end %>
 
<%= link_to 'Назад', collegial_path %>

app/views/collegials/index.html.erb
<h1>Коллегиальный орган:</h1>
<div>
  <%= link_to 'Новый', new_collegial_path, class: 'btn btn-primary' %>
</div>
<table class="table table-striped">
  <th>Название</th>
  <th>Адрес</th>
  <th>Номер телефона</th>  
  <% @collegial.each do |collegial| %>
    <tr>
        <td><%= link_to collegial.name, collegial %></td>
        <td><%= collegial.address %></td>
        <td><%= collegial.phone %></td>        
    </tr>
  <% end %>
</table>
 

app/views/collegials/new.html.erb
<h1>Новая коллегия </h1>

<%= form_for (@collegial) do |f| %>
  <p>
    <%= f.label :Название %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :Адрес %><br>
    <%= f.text_field :address %>
  </p>
  <p>
    <%= f.label :Телефон %><br>
    <%= f.text_field :phone %>
  </p>
  <p>
    <%= f.submit %>
  </p>
  <%= link_to 'Назад', collegials_path %>
<% end %>

app/views/collegials/show.html.erb
<h1>Название:</h1>
<p> 
  <%= @collegial.name %><br><br>
  <%= @collegial.address %><br><br>
  <%= @collegial.phone %><br><br>  
  <%= link_to 'Изменить', edit_collegial_path %>
  <%= link_to 'Удалить', collegial_path(@collegial), method: :delete, data: { confirm: 'Вы уверены?' } %>
</p>
<%= link_to 'Назад', collegials_path %>
 