config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  resources :type_of_activities
  resources :projects
  resources :collegials
  resources :type_of_movements
  resources :decisions
  resources :financial_indicators
  resources :indicator_values
  resources :inflows_outflows
  post 'inflows_outflows/export'
  resources :type_of_decisions

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
# == Schema Information
#
# Table name: admins
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_admins_on_email                 (email) UNIQUE
#  index_admins_on_reset_password_token  (reset_password_token) UNIQUE
#

class Admin < ApplicationRecord
    extend Devise::Models
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collegial.rb
# == Schema Information
#
# Table name: collegials
#
#  id         :integer          not null, primary key
#  name       :string
#  address    :string
#  phone      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Collegial < ApplicationRecord
  has_many :decisions
end

app/models/decision.rb
# == Schema Information
#
# Table name: decisions
#
#  id               :integer          not null, primary key
#  project_id       :integer
#  collegial_id     :integer
#  type_decision_id :integer
#  date_d           :date
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
# Indexes
#
#  index_decisions_on_collegial_id      (collegial_id)
#  index_decisions_on_project_id        (project_id)
#  index_decisions_on_type_decision_id  (type_decision_id)
#

class Decision < ApplicationRecord
  belongs_to :project
  belongs_to :type_decision, class_name: "TypeOfDecision"
  belongs_to :collegial
end

app/models/financial_indicator.rb
# == Schema Information
#
# Table name: financial_indicators
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class FinancialIndicator < ApplicationRecord
  has_many :indicator_values
end

app/models/indicator_value.rb
# == Schema Information
#
# Table name: indicator_values
#
#  id           :integer          not null, primary key
#  project_id   :integer
#  indicator_id :integer
#  value        :string
#  date_i       :date
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
# Indexes
#
#  index_indicator_values_on_indicator_id  (indicator_id)
#  index_indicator_values_on_project_id    (project_id)
#

class IndicatorValue < ApplicationRecord
  belongs_to :project
  belongs_to :indicator, class_name: "FinancialIndicator"
end

app/models/inflows_outflow.rb
# == Schema Information
#
# Table name: inflows_outflows
#
#  id          :integer          not null, primary key
#  movement_id :integer
#  project_id  :integer
#  total       :decimal(, )
#  date_f      :date
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  name        :string
#
# Indexes
#
#  index_inflows_outflows_on_movement_id  (movement_id)
#  index_inflows_outflows_on_project_id   (project_id)
#

class InflowsOutflow < ApplicationRecord
  belongs_to :movement, class_name: "TypeOfMovement"
  belongs_to :project
  
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id         :integer          not null, primary key
#  name       :string
#  currency   :string
#  date_p     :date
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Project < ApplicationRecord
  has_many :inflows_outflows
  has_many :indicator_values
  has_many :decisions
end

app/models/type_of_activity.rb
# == Schema Information
#
# Table name: type_of_activities
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class TypeOfActivity < ApplicationRecord
  has_many :type_of_movements, foreign_key: 'activity_id'
end

app/models/type_of_decision.rb
# == Schema Information
#
# Table name: type_of_decisions
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class TypeOfDecision < ApplicationRecord
  has_many :decisions
end

app/models/type_of_movement.rb
# == Schema Information
#
# Table name: type_of_movements
#
#  id          :integer          not null, primary key
#  name        :string
#  activity_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_type_of_movements_on_activity_id  (activity_id)
#

class TypeOfMovement < ApplicationRecord
  belongs_to :activity, class_name: "TypeOfActivity"
  has_many :inflows_outflows, foreign_key: 'movement_id'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord 
  extend Devise::Models
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :check_user!

  def index
    @project = Project.all
  end

  def show
    @project = Project.find(params[:id])
    @activities = TypeOfActivity.all
    @inflowsoutflow = InflowsOutflow.new
  end

  def new
    @project = Project.new
    @inflowsoutflow = InflowsOutflow.new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(project_params)
    @project.save

    redirect_to @project
  end

  def update
    @project = Project.find(params[:id])
    @project.assign_attributes(project_params)
    if @project.save
      flash[:success] = "Изменения сохранены."
      render :show
    else
      flash[:error] = "Ошибка! Изменения не сохранены"
      render :show
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to projects_path
  end

  private
  def project_params
    params.require(:project).permit(:name, :currency, :date_p)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :check_user!

  def index
    redirect_to new_user_session_path 
  end

  protected

  def check_user!
    redirect_to projects_path if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collegials_helper.rb
module CollegialsHelper
end

app/helpers/decisions_helper.rb
module DecisionsHelper
end

app/helpers/indicator_values_helper.rb
module IndicatorValuesHelper
end

app/helpers/inflows_outflows_helper.rb
module InflowsOutflowsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ASOIIU</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="row">
      <div class="col-xs-12">
        <%= render 'shared/header' %>
      </div>
    </div>

    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <div class="row">
        <div class="col-sm-12 col-md-2">
          <%= render 'shared/sidebar' %>
        </div>
        <div class="col-xs-10">
          <%= yield %>  
        </div>
      </div>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'ASOIIU', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user.present? %>
          <li>
            <%= link_to('Выход', destroy_user_session_path, :method => :delete) %> 
          </li>
        <% else %>
          <li>
            <%= link_to 'Регистрация', new_user_registration_path %>
          </li>
          <li>
            <%= link_to 'Вход', new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_sidebar.html.erb
<% if current_user %>
<ul class="nav nav-pills nav-stacked">
  <li>
    <%= link_to 'Проекты', projects_path %>
  </li>
  <li>
    <%= link_to 'Решения', decisions_path %>
  </li>
  <li>
    <%= link_to 'Значение', indicator_values_path %>
  </li>
  <li>
    <%= link_to 'Коллегиальный орган', collegials_path %>
  </li>
</ul>
<% end %>