config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  resources :type_of_activities
  resources :projects
  resources :collegials
  resources :type_of_movements
  resources :decisions
  resources :financial_indicators
  resources :indicator_values
  resources :inflows_outflows
  post 'inflows_outflows/export'
  resources :type_of_decisions

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id         :integer          not null, primary key
#  name       :string
#  currency   :string
#  date_p     :date
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Project < ApplicationRecord
  has_many :inflows_outflows
  has_many :indicator_values
  has_many :decisions
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :check_user!

  def index
    @project = Project.all
  end

  def show
    @project = Project.find(params[:id])
    @activities = TypeOfActivity.all
    @inflowsoutflow = InflowsOutflow.new
  end

  def new
    @project = Project.new
    @inflowsoutflow = InflowsOutflow.new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(project_params)
    @project.save

    redirect_to @project
  end

  def update
    @project = Project.find(params[:id])
    @project.assign_attributes(project_params)
    if @project.save
      flash[:success] = "Изменения сохранены."
      render :show
    else
      flash[:error] = "Ошибка! Изменения не сохранены"
      render :show
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to projects_path
  end

  private
  def project_params
    params.require(:project).permit(:name, :currency, :date_p)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<h1>Изменение Проекта</h1>
 
<%= form_for (@project) do |f| %>
  <%= f.label :Название %>
  <%= f.text_field :name %>
  <%= f.label :Валюта %>
  <%= f.text_field :currency %>
  <%= f.label :Дата_создания %>
  <%= f.date_field :date_p %>
  <%= f.submit :Сохранить%>
<% end %>
 
<%= link_to 'Назад', projects_path %>

app/views/projects/index.html.erb
<h1>Проекты:</h1>
<div class="form-group">
  <%= link_to 'Новый проект', new_project_path, class: "btn btn-primary"%>
</div>
<table class="table table-striped">
  <th>Название проекта</th>
  <th>Валюта</th>
  <th>Дата создания</th>
  <% @project.each do |project| %>
      <tr>
        <td><%= link_to project.name, project %></td>
        <td><%= project.currency %></td>
        <td><%= project.date_p %></td>
      </tr>
  <% end %>
</table>
 

app/views/projects/new.html.erb
<h1>Новый проект</h1>

<%= form_for (@project) do |f| %>
  <p>
    <%= f.label :Название %><br>
    <%= f.text_field :name %>
    <%= f.label :Валюта %>
    <%= f.text_field :currency %>
    <%= f.label :Дата_создания %>
    <%= f.date_field :date_p %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/projects/show.html.erb
<h1>Проект <%= @project.name %>:</h1>
<div>
  <h3 class="text-center">
    <%= @project.name %>
  </h3>
</div>

<% date = @project.date_p  %>  
<% dates = (date..(date.months_since(6))).map{|d| [Russian::strftime(d, "%B %Y"), d.month, d.year] }.uniq %>

<% grouped_data = @project.inflows_outflows.group_by { |inout| [inout.movement, inout.movement.activity, inout.date_f.month, inout.date_f.year] } %>

    <table class="table table-striped table-bordered">
      <thead>
        <th>Старт <%= @project.date_p %> </th>
          <% dates.each_with_index do |month_array, i| %>
            <% month_label = month_array[0] %>
              <th><%= month_label %></th>
          <% end %>
      </thead>
      <tbody>
        <% @activities.each do |activity| %>
            <tr>
              <td><b><%= activity.name %></b></td>  
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
            </tr>
            <% activity.type_of_movements.order(name: 'DESC').each do |movement| %>
              <tr >
                <% check_movement = movement %>
                <td class="text-underline newinout" data-month="<%= dates.first[1] %>" data-year="<%= dates.first[2] %>" data-project-id="<%= @project.id %>" data-movement-id="<%= movement.id %>"><i><%= movement.name %></i></td>
                
                <% dates.each_with_index do |month_array, i| %>
                  <% month = month_array[1] %>
                  <% year = month_array[2] %>
                  <% grouped_data_filtered = grouped_data.select { |movement_activity_month, inouts| movement_activity_month[1] == activity }.select { |movement_activity_month, inouts| movement_activity_month[0] == movement } %>
                  
                  <% if grouped_data_filtered.present? %>
                    <% result = grouped_data_filtered.find { |movement_activity_month, inouts| movement_activity_month[2] == month && movement_activity_month[3] == year } %>
                    <td class="sum-movement" data-month="<%= month %>" data-year="<%= year %>" data-activity-id="<%= activity.id %>" data-movement-id="<%= movement.id %>"><%= result && result[1].sum(&:total) %></td>
                  <% else %>
                    <td></td>
                  <% end %>
                <% end %>
              </tr>
              <% movement.inflows_outflows.where(project: @project).order(name: "DESC").group_by(&:name).each do |inout_name, inouts| %>
                <tr>
                  <td><%= inout_name %></td>
                  <% dates.each_with_index do |month_array, i| %>
                    <% month = month_array[1] %>
                    <% year = month_array[2] %>

                    <% if inouts.pluck(:date_f).map { |d| [d.month, d.year] }.include?([month, year]) %>
                      <% inout = inouts.select {|i| i.date_f.month == month && i.date_f.year == year }.first %>
                      <td id="column-total" data-month="<%= month %>" data-year="<%= year %>" data-activity-id="<%= movement.activity.id %>" data-movement-id="<%= movement.id %>"><%= best_in_place inout, :total %></td>
                    <% else %>
                      <td class="yearmonth" data-name="<%= inout_name %>" data-movement-id="<%= movement.id %>" data-project-id="<%= @project.id %>" data-month="<%= month %>" data-year="<%= year %>"></td>
                    <% end %>
                    <% if false %>
                      <% if inout.date_f.month == month && inout.date_f.year == year %>
                        <td id="column-total" data-month="<%= month %>" data-year="<%= year %>" data-activity-id="<%= movement.activity.id %>" data-movement-id="<%= movement.id %>"><%= best_in_place inout, :total %></td>
                      <% else %>
                        <%# best_in_place InflowsOutflow.new(movement: movement, project: @project, date_f: DateTime.new(year, month, 1), name: inout.name), :total %>
                        <td class="yearmonth" data-toggle="modal" data-name="<%= inout.name %>" data-movement-id="<%= movement.id %>" data-project-id="<%= @project.id %>" data-month="<%= month %>" data-year="<%= year %>"></td>
                      <% end %>
                    <% end %>
                  <% end %>
                </tr>
              <% end %>
            <% end %>
        <% end %>
      </tbody>
    </table>
    <div>
      <% snpv = [] %>
      <% inf = [] %>
      <% out = [] %>
      <% @activities.each do |activity| %>
        <% summ = [] %>
        <% activity.type_of_movements.where("name LIKE ?", "Притоки").each do |movement| %>
          <% dates.each_with_index do |month_array, i| %>
            <% month = month_array[1] %>
            <% year = month_array[2] %>
            <% grouped_data_filtered = grouped_data.select { |movement_activity_month, inouts| movement_activity_month[1] == activity }.select { |movement_activity_month, inouts| movement_activity_month[0] == movement } %>
            <% if grouped_data_filtered.present? %>
              <% result = grouped_data_filtered.find { |movement_activity_month, inouts| movement_activity_month[2] == month && movement_activity_month[3] == year } %>
              <% summ << (result && (result[1].sum(&:total))) %>
              
            <% end %>
          <% end %>
          <%# summ.delete_if(&:nil?).sum %>
          <% summ.delete_if(&:nil?).each do |s| %>
            <% inf << s %>
          <% end %>
        <% end %>

        <% activity.type_of_movements.where("name LIKE ?", "Оттоки").each do |movement| %>
          <% tmp = [] %>
          <% dates.each_with_index do |month_array, i| %>
            <% month = month_array[1] %>
            <% year = month_array[2] %>
            <% grouped_data_filtered = grouped_data.select { |movement_activity_month, inouts| movement_activity_month[1] == activity }.select { |movement_activity_month, inouts| movement_activity_month[0] == movement } %>
            
            <% if grouped_data_filtered.present? %>
              <% result = grouped_data_filtered.find { |movement_activity_month, inouts| movement_activity_month[2] == month && movement_activity_month[3] == year } %>
              <% tmp << (result && (result[1].sum(&:total))) %>
            <% end %>
          <% end %>
          <%# snpv << summ.delete_if(&:nil?).sum + tmp.delete_if(&:nil?).sum %>
          <% tmp.delete_if(&:nil?).each do |t| %>
            <% out << t %>
          <% end %>
        <% end %>

      <% end %>
      NPV:
      <% i_count = [inf.count, out.count].max  %>
      <%= i_count.times.map { |i| (((inf[i] || 0) - (out[i] || 0)) / (1 + 0.1) ** i).round(2) }.sum %>
      <br/>
    </div>
<%= link_to 'Назад', projects_path %>
<%= link_to 'Изменить', edit_project_path %>
<%= link_to 'Удалить', project_path(@project), method: :delete, data: { confirm: 'Вы уверены?' } %>